[tool.poetry]
name = "chatgpt-clone-django"
version = "0.1.0"
description = ""
authors = ["takuyakato"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.30.1"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
